### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by ghost**
i'm still not finished! please have it reviewed

this PR will allow to support more distributions other than alpine. using `proot-distro` as an engine

by default it will use alpine, by setting `CNF_OS_TYPE`  variable to `debian` or `arch` will use that distribution

for remote uninstallation, just specify `export CNF_UNINSTALL=1` to trigger uninstallation of the distribution

and to disable. specify `CNF_DISABLE=1` variable

### CODE REVIEW

**Comment by Yonle** [comment]
Well. That would better to do something else. Gonna test it out.

**Review by Yonle — CHANGES_REQUESTED** [review]
This command-not-found is better to put it to `install.sh` script. To be clever, The `command-not-found` code should be inside `install.sh` file instead.

**Comment by ghost** [comment]
maybe though i thought it would be better for install.sh to `install` files in directories

**Comment by Yonle** [comment]
Well, maybe writting those all fish script inside `install.sh` would OK. I may check it later

**Comment by Yonle** [comment]
Closing due to inactivity. You may open new PR once you're done

**Pull request closed without merging**
